default:
  dir_name: outputs
  resource: local
  bar: False
  r_seed: 317
  num_workers: 0
  eval_freq: 1
  epochs: 1000
  save: False
  multi_node: False
  master: "localhost"
  port: 1234
  DDP: True
  rapid: True
  amp: True
  finetune: False
  wandb: False

network:
  dnn_task: counting
  backbone: vgg16_bn
  set_cost_class: 1.0
  set_cost_point: 0.05
  point_loss_coef: 0.0002
  class_loss_coef: 1.0
  eos_coef: 0.5
  row: 2
  line: 2
  matcher_cal: gpu
  clip_max_norm: 0.1
  all_save: False
  fix_param: None
  init_weight: ImageNet

dataset:
  cache: True
  name: ShanghaiB
  crop_size: 128
  crop_freq: 4
  cut_out: False
  color_jitter: False
  brightness: 30
  contrast: 0
  saturation: 30
  hue: 5

optimizer:
  hp:
    lr: 0.1
    lr_decay: 0.001
    momentum: 0.95
    weight_decay: 0.0001
    lr_warmup_step: 10
    lr_warmup_init: 1e-5
  batch_size:
    train: 2
    test: 1
  scheduler:
    name: cosine
    step: 3500
    warmup: False

wandb:
  project_name: "MIRU_demo"
  run_name: ""

# sampler:
#   iteration: 50
#   params:
#     - {min_val: 1.0, max_val: 6.0, name: lr, type: float, groups: "optimizer" }
#     - {min_val: 0.8,max_val: 1.0, name: momentum, type: float}
#     - {min_val: 2.0,max_val: 8.0, name: weight_decay, type: float}
#     - {min_val: 0.0001, max_val: 0.5,name: lr_decay,type: float}
