experiment_name: "demo_hydra"
job_id: null
hydra:
  run:
    dir: ./outputs/${experiment_name}


defaults:
  - _self_
  - execution: default
  - pipeline: default

settings:
  #====入力設定====
  video_path: "demo.mov"
  save_dir: "${hydra:runtime.output_dir}/results"
  weight_path: "cutout.pth"
  bev_file: "crs/bev/WorldPorters_8K_matrix.txt"
  size_file: "crs/size/WorldPorters_8K_size.txt"
  #====可視化設定====
  detection_vis_freq: 30
  track_vis_freq: 5
  multi_video_mode: False
  # track_vis_start_frame: 1
  # track_vis_end_frame: 200
  #====出力設定====
  img_dir: "${settings.save_dir}/img"
  img_extension: "png"
  detection_output_dir: "${settings.save_dir}/detection"
  detection_data_dir: "${settings.save_dir}/detection/frame_detection"
  track_dir: "${settings.save_dir}/track"
  risk_output_dir: "${settings.save_dir}/crowd_risk_score"     
  detection_vis_dir: "${settings.save_dir}/detection_vis_${settings.detection_vis_freq}"
  track_vis_dir: "${settings.save_dir}/track_vis_${settings.track_vis_freq}"
  risk_vis_dir: "${settings.save_dir}/risk_vis"
  time_log_file: "${settings.save_dir}/time_log.txt"
