output_dir: demo/crowd_risk_score/debug
track_dir: demo/track
bev_file: crs/bev/WorldPorters_8K_matrix.txt
size_file: crs/size/WorldPorters_8K_size.txt
crop_area: null
frame_range:
- 1
- 151
# - 8900
freq: 10
func_para:
- 1
- 13.5
- null
grid_size: 5
vec_span: 10
dan_ver: div
distance_decay_method: gaussian
vec_decay_method: null
